apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-proxy-config
  namespace: kube-system
  labels:
    k8s-app: kube-proxy
    pipeline-managed: "true"
data:
  kube-proxy.config: |
    apiVersion: kubeproxy.config.k8s.io/v1alpha1
    bindAddress: 0.0.0.0
    clientConnection:
      acceptContentTypes: ""
      burst: 10
      contentType: application/vnd.kubernetes.protobuf
      kubeconfig: "/etc/k8s/kube.config"
      qps: 5
    clusterCIDR: "100.72.0.0/16"
    configSyncPeriod: 15m0s
    conntrack:
      max: 0
      maxPerCore: 32768
      min: 131072
      tcpCloseWaitTimeout: 1h0m0s
      tcpEstablishedTimeout: 24h0m0s
    enableProfiling: false
    featureGates: {}
    healthzBindAddress: 0.0.0.0:10256
    iptables:
      masqueradeAll: false
      masqueradeBit: 14
      minSyncPeriod: 0s
      syncPeriod: 30s
    kind: KubeProxyConfiguration
    metricsBindAddress: 0.0.0.0:10249
    mode: "iptables"
    oomScoreAdj: -999
    portRange: ""
    resourceContainer: /kube.slice/kube-proxy
    udpTimeoutMilliseconds: 250ms
  kube.config: |
    apiVersion: v1
    kind: Config
    clusters:
    - name: in-cluster
      cluster:
        certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        server: https://127.0.0.1:11000
    users:
    - name: 'system:kube-proxy'
      user:
        tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    contexts:
    - context:
        cluster: in-cluster
        user: 'system:kube-proxy'
      name: kube-proxy-context
    current-context: kube-proxy-context
